apiVersion: v1
kind: Service
metadata:
  name: pixiegateway-service
spec:
  selector:
    app: pixiegateway
  ports:
    - protocol: TCP
      port: 8888
      name: "pixiegateway"
      nodePort: 32222
  type: NodePort
